services:
  dispatcharr-maid-web:
    environment:
      DISPATCHARR_AUTH_ENABLED: "true"
      DISPATCHARR_USERNAME: "gregw"
      DISPATCHARR_PASSWORD_HASH: "32768:8:1$$Ro54BrBGZlCt76MH$$ed3ac8b786b1e5e98aa5a83f50705e0898d28aeaba8e68c1604874a5ef410920ade557ea208c8cfe535d3378808f9ee00edfc44c1947a969e40f8995989d2042"
      DISPATCHARR_SECRET_KEY: "gwysbnhvt"
